-- MySQL Script generated by MySQL Workbench
-- qui 30 jan 2020 11:30:34 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avistdb
-- -----------------------------------------------------
-- Banco de Dados do Sistema de Rota da Vinícolas - Avist.

-- -----------------------------------------------------
-- Schema avistdb
--
-- Banco de Dados do Sistema de Rota da Vinícolas - Avist.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avistdb` DEFAULT CHARACTER SET utf8 ;
USE `avistdb` ;

-- -----------------------------------------------------
-- Table `avistdb`.`TipoEmpresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`TipoEmpresa` (
  `codTipoEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nomeTipoEmpresa` TINYTEXT NULL,
  PRIMARY KEY (`codTipoEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avistdb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Empresa` (
  `codEmpresa` INT NOT NULL AUTO_INCREMENT,
  `TipoEmpresa_codTipoEmpresa` INT NOT NULL,
  `nomeEmpresa` TINYTEXT NULL,
  `infos` TINYTEXT NULL,
  `biografia` TINYTEXT NULL,
  `email` TINYTEXT NULL,
  `linkGoogleMaps` TINYTEXT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  PRIMARY KEY (`codEmpresa`),
  INDEX `fk_Empresa_TipoEmpresa1_idx` (`TipoEmpresa_codTipoEmpresa` ASC),
  CONSTRAINT `fk_Empresa_TipoEmpresa1`
    FOREIGN KEY (`TipoEmpresa_codTipoEmpresa`)
    REFERENCES `avistdb`.`TipoEmpresa` (`codTipoEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avistdb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Pessoa` (
  `codPessoa` INT NOT NULL AUTO_INCREMENT,
  `Empresa_codEmpresa` INT NOT NULL,
  `nome` TINYTEXT NULL COMMENT '	',
  `email` TINYTEXT NULL,
  PRIMARY KEY (`codPessoa`),
  INDEX `fk_Pessoa_Empresa1_idx` (`Empresa_codEmpresa` ASC),
  CONSTRAINT `fk_Pessoa_Empresa1`
    FOREIGN KEY (`Empresa_codEmpresa`)
    REFERENCES `avistdb`.`Empresa` (`codEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avistdb`.`TipoContato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`TipoContato` (
  `codTipoContato` INT NOT NULL AUTO_INCREMENT,
  `nomeTipoContato` TINYTEXT NULL,
  PRIMARY KEY (`codTipoContato`))
ENGINE = InnoDB
COMMENT = 'Identifica os tipos de formas de contato com a empresa (Telefones / Redes sociais).';


-- -----------------------------------------------------
-- Table `avistdb`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Contato` (
  `codContato` INT NOT NULL AUTO_INCREMENT,
  `Empresa_codEmpresa` INT NOT NULL,
  `TipoContato_TipoContato` INT NOT NULL,
  `descContato` TINYTEXT NULL COMMENT 'Informar o número do telefone ou o perfil da empresa nas redes sociais.',
  PRIMARY KEY (`codContato`),
  INDEX `fk_TelefoneEmpresa_Empresa1_idx` (`Empresa_codEmpresa` ASC),
  INDEX `fk_Contato_TipoContato1_idx` (`TipoContato_TipoContato` ASC),
  CONSTRAINT `fk_TelefoneEmpresa_Empresa1`
    FOREIGN KEY (`Empresa_codEmpresa`)
    REFERENCES `avistdb`.`Empresa` (`codEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contato_TipoContato1`
    FOREIGN KEY (`TipoContato_TipoContato`)
    REFERENCES `avistdb`.`TipoContato` (`codTipoContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Informação sobre os telefones e as redes sociais da empresa.';


-- -----------------------------------------------------
-- Table `avistdb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Endereco` (
  `codEndereco` INT NOT NULL AUTO_INCREMENT,
  `Empresa_codEmpresa` INT NOT NULL,
  `rua` TINYTEXT NULL,
  `cidade` TINYTEXT NULL,
  `bairro` TINYTEXT NULL,
  `numero` TINYTEXT NULL,
  `referencia` TINYTEXT NULL,
  `logradouro` TINYTEXT NULL,
  PRIMARY KEY (`codEndereco`),
  INDEX `fk_Endereco_Empresa1_idx` (`Empresa_codEmpresa` ASC),
  CONSTRAINT `fk_Endereco_Empresa1`
    FOREIGN KEY (`Empresa_codEmpresa`)
    REFERENCES `avistdb`.`Empresa` (`codEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avistdb`.`TipoImagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`TipoImagem` (
  `codTipoImagem` INT NOT NULL AUTO_INCREMENT,
  `nomeTipoImagem` TINYTEXT NULL,
  PRIMARY KEY (`codTipoImagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avistdb`.`Imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Imagem` (
  `codImagem` INT NOT NULL AUTO_INCREMENT,
  `Empresa_codEmpresa` INT NOT NULL,
  `TipoImagem_codTipoImagem` INT NOT NULL,
  `pathImagem` TINYTEXT NULL,
  `descImagem` TINYTEXT NULL,
  `ordemApresentacao` VARCHAR(45) NULL,
  PRIMARY KEY (`codImagem`),
  INDEX `fk_Imagem_Empresa1_idx` (`Empresa_codEmpresa` ASC),
  INDEX `fk_Imagem_TipoImagem1_idx` (`TipoImagem_codTipoImagem` ASC),
  CONSTRAINT `fk_Imagem_Empresa1`
    FOREIGN KEY (`Empresa_codEmpresa`)
    REFERENCES `avistdb`.`Empresa` (`codEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imagem_TipoImagem1`
    FOREIGN KEY (`TipoImagem_codTipoImagem`)
    REFERENCES `avistdb`.`TipoImagem` (`codTipoImagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avistdb`.`TipoInformacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`TipoInformacao` (
  `codTipoInformacao` INT NOT NULL AUTO_INCREMENT,
  `descTipoInformacao` TINYTEXT NULL,
  PRIMARY KEY (`codTipoInformacao`))
ENGINE = InnoDB
COMMENT = 'Identifica os tipos de informações da empresa (Ex.: Histórico, Descrição da Empresa, Missão, Valores)';


-- -----------------------------------------------------
-- Table `avistdb`.`Informacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Informacao` (
  `codInformacao` INT NOT NULL AUTO_INCREMENT,
  `TipoInformacao_codTipoInformacao` INT NOT NULL,
  `Empresa_codEmpresa` INT NOT NULL,
  `descInformacao` TEXT NULL,
  PRIMARY KEY (`codInformacao`),
  INDEX `fk_Informacao_Empresa1_idx` (`Empresa_codEmpresa` ASC),
  INDEX `fk_Informacao_TipoInformacao1_idx` (`TipoInformacao_codTipoInformacao` ASC),
  CONSTRAINT `fk_Informacao_Empresa1`
    FOREIGN KEY (`Empresa_codEmpresa`)
    REFERENCES `avistdb`.`Empresa` (`codEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Informacao_TipoInformacao1`
    FOREIGN KEY (`TipoInformacao_codTipoInformacao`)
    REFERENCES `avistdb`.`TipoInformacao` (`codTipoInformacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Armazena as descrições sobre a empresa.';


-- -----------------------------------------------------
-- Table `avistdb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Produto` (
  `codProduto` INT NOT NULL AUTO_INCREMENT,
  `Empresa_codEmpresa` INT NOT NULL,
  `nomeProduto` TINYTEXT NULL,
  `descProduto` TINYTEXT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`codProduto`),
  INDEX `fk_Produto_Empresa1_idx` (`Empresa_codEmpresa` ASC),
  CONSTRAINT `fk_Produto_Empresa1`
    FOREIGN KEY (`Empresa_codEmpresa`)
    REFERENCES `avistdb`.`Empresa` (`codEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Identifica os produtos disponibilizados pela empresa. A coluna Ativo indica se o produto deve ou não aparecer nas listagens.';


-- -----------------------------------------------------
-- Table `avistdb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avistdb`.`Servico` (
  `codServico` INT NOT NULL AUTO_INCREMENT,
  `Empresa_codEmpresa` INT NOT NULL,
  `descServico` TINYTEXT NULL,
  `descHorario` TINYTEXT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`codServico`),
  INDEX `fk_Servico_Empresa1_idx` (`Empresa_codEmpresa` ASC),
  CONSTRAINT `fk_Servico_Empresa1`
    FOREIGN KEY (`Empresa_codEmpresa`)
    REFERENCES `avistdb`.`Empresa` (`codEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Identifica os serviços disponibilizados pela empresa. A coluna Ativo indica se o serviço deve ou não aparecer nas listagens.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `avistdb`.`TipoEmpresa`
-- -----------------------------------------------------
START TRANSACTION;
USE `avistdb`;
INSERT INTO `avistdb`.`TipoEmpresa` (`codTipoEmpresa`, `nomeTipoEmpresa`) VALUES (DEFAULT, 'Associação');
INSERT INTO `avistdb`.`TipoEmpresa` (`codTipoEmpresa`, `nomeTipoEmpresa`) VALUES (DEFAULT, 'Vinícola / Cantina');
INSERT INTO `avistdb`.`TipoEmpresa` (`codTipoEmpresa`, `nomeTipoEmpresa`) VALUES (DEFAULT, 'Parceiro');
INSERT INTO `avistdb`.`TipoEmpresa` (`codTipoEmpresa`, `nomeTipoEmpresa`) VALUES (DEFAULT, 'Colaborador');

COMMIT;


-- -----------------------------------------------------
-- Data for table `avistdb`.`TipoContato`
-- -----------------------------------------------------
START TRANSACTION;
USE `avistdb`;
INSERT INTO `avistdb`.`TipoContato` (`codTipoContato`, `nomeTipoContato`) VALUES (DEFAULT, 'Telefone Fixo');
INSERT INTO `avistdb`.`TipoContato` (`codTipoContato`, `nomeTipoContato`) VALUES (DEFAULT, 'Whatsapp');
INSERT INTO `avistdb`.`TipoContato` (`codTipoContato`, `nomeTipoContato`) VALUES (DEFAULT, 'Email');
INSERT INTO `avistdb`.`TipoContato` (`codTipoContato`, `nomeTipoContato`) VALUES (DEFAULT, 'Facebook');
INSERT INTO `avistdb`.`TipoContato` (`codTipoContato`, `nomeTipoContato`) VALUES (DEFAULT, 'Instagram');
INSERT INTO `avistdb`.`TipoContato` (`codTipoContato`, `nomeTipoContato`) VALUES (DEFAULT, 'Twitter');
INSERT INTO `avistdb`.`TipoContato` (`codTipoContato`, `nomeTipoContato`) VALUES (DEFAULT, 'YouTube');

COMMIT;


-- -----------------------------------------------------
-- Data for table `avistdb`.`TipoImagem`
-- -----------------------------------------------------
START TRANSACTION;
USE `avistdb`;
INSERT INTO `avistdb`.`TipoImagem` (`codTipoImagem`, `nomeTipoImagem`) VALUES (DEFAULT, 'Logomarca');
INSERT INTO `avistdb`.`TipoImagem` (`codTipoImagem`, `nomeTipoImagem`) VALUES (DEFAULT, 'Carrossel');
INSERT INTO `avistdb`.`TipoImagem` (`codTipoImagem`, `nomeTipoImagem`) VALUES (DEFAULT, 'Fotos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `avistdb`.`TipoInformacao`
-- -----------------------------------------------------
START TRANSACTION;
USE `avistdb`;
INSERT INTO `avistdb`.`TipoInformacao` (`codTipoInformacao`, `descTipoInformacao`) VALUES (DEFAULT, 'Histórico');
INSERT INTO `avistdb`.`TipoInformacao` (`codTipoInformacao`, `descTipoInformacao`) VALUES (DEFAULT, 'Descrição da Empresa');
INSERT INTO `avistdb`.`TipoInformacao` (`codTipoInformacao`, `descTipoInformacao`) VALUES (DEFAULT, 'Missão');
INSERT INTO `avistdb`.`TipoInformacao` (`codTipoInformacao`, `descTipoInformacao`) VALUES (DEFAULT, 'Valores');
INSERT INTO `avistdb`.`TipoInformacao` (`codTipoInformacao`, `descTipoInformacao`) VALUES (DEFAULT, 'Outros');

COMMIT;

